{% set name = "moola" %}
{% set version = "0.1.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9b5936cef0d2a29432784dea9e4813e3653d5277a66bac67bf5d89ba912ec7ce
  patches:
    # FIXME: this patch is merged upstream, remove in 0.1.7
    - imports.patch

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - numpy

test:
  requires:
    - python {{ python_min }}
  imports:
    - moola

about:
  home: https://github.com/funsim/moola
  license: LGPL 3
  license_family: LGPL
  # FIXME: license file is missing from sdist in 0.1.6
  # this is fixed in master
  # license_file: LICENSE
  summary: 'Moola implements a set of optimisation algorithms with a special focus on PDE-constrained optimisation problems.'
  dev_url: https://github.com/funsim/moola

extra:
  recipe-maintainers:
    - funsim
    - minrk
    - sebastkm
